# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import example_pb2 as example__pb2


class ExampleServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExampleServer = channel.unary_unary(
        '/hagaeru3sei.ExampleService/ExampleServer',
        request_serializer=example__pb2.Request.SerializeToString,
        response_deserializer=example__pb2.Reply.FromString,
        )


class ExampleServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExampleServer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExampleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExampleServer': grpc.unary_unary_rpc_method_handler(
          servicer.ExampleServer,
          request_deserializer=example__pb2.Request.FromString,
          response_serializer=example__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hagaeru3sei.ExampleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
